name: Unit Tests

<<<<<<< HEAD
=======
permissions:
  contents: read

>>>>>>> upstream/master
on:
  push:
    branches:
    - master
    - develop
  pull_request:
    paths:
    - 'builddefs/**'
    - 'quantum/**'
    - 'platforms/**'
    - 'tmk_core/**'
    - 'tests/**'
    - '*.mk'
    - 'Makefile'
    - '.github/workflows/unit_test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run tests
      run: make test:all
=======
    container: ghcr.io/qmk/qmk_cli

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements-dev.txt
    - name: Run tests
      run: qmk test-c
>>>>>>> upstream/master
